package pkgMain;

import java.util.*;


/**
 * Controller of the program
 * @author Matthew
 *
 */
public class GardenController {

	Plot view;
	Model model = new Model();
	
	public GardenController() throws Exception {
		model.parse();
	}

	/**
	 * 
	 * Getter for the array list of all plants generated by the parser in model
	 * @throws Exception
	 */
	public ArrayList<Plant> getPlantAL() throws Exception {
		return model.plantList;
	}
	/**
	 * Gets the current arraylist of all of the plants in the basket
	 * @return 
	 * @throws Exception
	 */
	public ArrayList<Plant> getBasket() throws Exception {
		return model.getBasket();
	}
	/**
	 * Gets all of the plants within the plot
	 * @return
	 * @throws Exception
	 */
	public static ArrayList<Plant> getPlants() throws Exception {
		return Plot.getPlantsInPlot();
	}
	/**
	 * Adds a plant to the basket
	 * @param p Plant to be added
	 * @throws Exception
	 */
	public void addToBasket(Plant p) throws Exception {
		model.addToBasket(p);
	}
	/**
	 * Removes a specific plant from the basket.
	 * @param p Plant to be removed.
	 * @throws Exception
	 */
	public void removeFromBasket(Plant p) throws Exception {
		model.removeFromBasket(p);
	}
	
	//Just getters and setters for the inputs from GardenConditions.
	public String getSoil() {
		return model.getSoil();
	}

	public void setSoil(String soil) {
		model.setSoil(soil);
	}

	public String getSun() {
		return model.getSun();
	}

	public void setSun(String sun) {
		model.setSun(sun);
	}

	public String getMoisture() {
		return model.getMoisture();
	}

	public void setMoisture(String moisture) {
		model.setMoisture(moisture);
	}
	
	public int getBudget() {
		return model.getBudget();
	}

	public void setBudget(int budget) {
		model.setBudget(budget);
	}
}
